/**
 * Created by Administrator on 2016/11/25.
 */
export default {
  "attachDataInfo": [{
    "attachColmName": "附件列表",
    "fileId": "504855",
    "fileInformation": "",
    "fileName": "cports_2.32_XiaZaiBa.zip",
    "fileSize": "",
    "fileSort": "1",
    "fileType": "",
    "uploadMan": "",
    "uploadTime": ""
  }, {
    "attachColmName": "附件列表",
    "fileId": "504856",
    "fileInformation": "附件说明333",
    "fileName": "desktop.ini",
    "fileSize": "",
    "fileSort": "2",
    "fileType": "",
    "uploadMan": "",
    "uploadTime": ""
  }, {
    "attachColmName": "附件列表",
    "fileId": "504857",
    "fileInformation": "附件说明666",
    "fileName": "职位缺编信息2017-11-21-110247.xls",
    "fileSize": "",
    "fileSort": "3",
    "fileType": "",
    "uploadMan": "",
    "uploadTime": ""
  }],
  "bodyDataInfo": [],
  "documentDataInfo": [{
    "colmName": "MEIP_DealStatus",
    "colmSort": "1",
    "colmType": "TEXT",
    "colmValue": "报销处理状态：->部门领导审核"
  }, {
    "colmName": "MEIP_BillType",
    "colmSort": "2",
    "colmType": "TEXT",
    "colmValue": ""
  }, {
    "colmName": "MEIP_DocTitle",
    "colmSort": "3",
    "colmType": "TEXT",
    "colmValue": "中国移动通信集团广西有限公司资金划拨报销审批单"
  }, {
    "colmName": "报销单编号",
    "colmSort": "4",
    "colmType": "TEXT",
    "colmValue": "QU171122155002"
  }, {
    "colmName": "起草时间",
    "colmSort": "5",
    "colmType": "TEXT",
    "colmValue": "2017-11-22+10:36:23"
  }, {
    "colmName": "员工姓名",
    "colmSort": "6",
    "colmType": "TEXT",
    "colmValue": "潘能冬"
  }, {
    "colmName": "员工编号",
    "colmSort": "7",
    "colmType": "TEXT",
    "colmValue": "33250842"
  }, {
    "colmName": "电子邮箱",
    "colmSort": "8",
    "colmType": "TEXT",
    "colmValue": "pannengdong@gx.chinamobile.com"
  }, {
    "colmName": "手机号码",
    "colmSort": "9",
    "colmType": "TEXT",
    "colmValue": "13877166622"
  }, {
    "colmName": "报销部门",
    "colmSort": "10",
    "colmType": "TEXT",
    "colmValue": "广西财务部财务管理室"
  }, {
    "colmName": "员工职务",
    "colmSort": "11",
    "colmType": "TEXT",
    "colmValue": "广西财务部财务管理室预算考核管理"
  }, {
    "colmName": "借方总金额:",
    "colmSort": "12",
    "colmType": "TEXT",
    "colmValue": "27.00"
  }, {
    "colmName": "借方总金额(大写)",
    "colmSort": "13",
    "colmType": "TEXT",
    "colmValue": "贰拾柒元整"
  }, {
    "colmName": "贷方总金额:",
    "colmSort": "14",
    "colmType": "TEXT",
    "colmValue": "27.00"
  }, {
    "colmName": "贷方总金额(大写)",
    "colmSort": "15",
    "colmType": "TEXT",
    "colmValue": "贰拾柒元整"
  }, {
    "colmName": "报销事由",
    "colmSort": "16",
    "colmType": "TEXT",
    "colmValue": "午饭黄焖鸡米饭报销"
  }, {
    "colmName": "备注",
    "colmSort": "17",
    "colmType": "TEXT",
    "colmValue": "备注+2017年11月22日+10:36:50"
  }, {
    "colmName": "借方总金额:",
    "colmSort": "18",
    "colmType": "TEXT",
    "colmValue": ""
  }, {
    "colmName": "贷方总金额:",
    "colmSort": "19",
    "colmType": "TEXT",
    "colmValue": ""
  }, {
    "colmName": "附件列表",
    "colmSort": "20",
    "colmType": "ATTACH",
    "colmValue": "MtvTab"
  }, {
    "colmName": "费用明细列表",
    "colmSort": "21",
    "colmType": "TABLE",
    "colmValue": "TAB_FEE_DETAILS"
  }],
  "errFlag": "N",
  "errMsg": "",
  "multiLevel": ""
}
